"""empty message

Revision ID: 5d7d05b3a678
Revises: d4bfcbc75339
Create Date: 2023-09-07 08:42:38.104020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7d05b3a678'
down_revision = 'd4bfcbc75339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisor_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekNo', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisor_activity', schema=None) as batch_op:
        batch_op.drop_column('weekNo')

    # ### end Alembic commands ###
