"""empty message

Revision ID: d4bfcbc75339
Revises: de6e254f2e57
Create Date: 2023-09-06 19:29:08.800292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4bfcbc75339'
down_revision = 'de6e254f2e57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('otp', sa.String(length=6), nullable=False))
        batch_op.add_column(sa.Column('expiration_time', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisor', schema=None) as batch_op:
        batch_op.drop_column('expiration_time')
        batch_op.drop_column('otp')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
