"""empty message

Revision ID: eaa734e630a4
Revises: 41d2e5e9d1c1
Create Date: 2023-09-12 17:13:47.862282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa734e630a4'
down_revision = '41d2e5e9d1c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('supervisorName',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    with op.batch_alter_table('supervisor_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisor_activity', schema=None) as batch_op:
        batch_op.drop_column('student_id')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('supervisorName',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###
